### ISSUE TITLE
Specialized 'XAMusic' Objects not Returned by Filters

### ISSUE THREAD

**Issue by MizterB** [SKaplanOfficial/PyXA#10]
Similar to what was addressed in #8 , I am seeing more instances of XAMedia base objects being returned in the Music app, rather than their specialized XAMusic variants.

See example below.  If I try to filter a `XAMusicUserPlaylistList`, the resulting objects are of the `XAMediaUserPlaylist` base class.

Example:
```
PyXA.Music().user_playlists()
<<class 'PyXA.apps.Music.XAMusicUserPlaylistList'>length: 1171>

PyXA.Music().user_playlists().first
<PyXA.apps.Music.XAMusicUserPlaylist object at 0x106c9e260>

PyXA.Music().user_playlists().by_name("MY PLAYLIST")
<PyXA.apps.MediaApplicationBase.XAMediaUserPlaylist object at 0x106c2ff70>

PyXA.Music().user_playlists().by_property("name", "MY PLAYLIST")
<PyXA.apps.MediaApplicationBase.XAMediaUserPlaylist object at 0x106c9fca0>
```

**Comment by SKaplanOfficial** [comment]
Thanks for reporting, fixed in the upcoming release -- at least for Music. I'll need to see if this is a problem in other applications as well.
