### ISSUE TITLE
Error when creating new note in Notes

### ISSUE THREAD

**Issue by MizterB** [SKaplanOfficial/PyXA#13]
When following the example:
`PyXA.Application("Notes").new_note("PyXA Notes", "Example text of new note.")` 

An exception is raised: `AttributeError: 'str' object has no attribute 'text'`

Seems to be related to https://github.com/SKaplanOfficial/PyXA/commit/03d9d2c02d56e1c8c28161fdf85b77ae3bf80c92#diff-19878d8e9796a90d6a6ceb11f8fa1c85383268842ea68ff71fc2ce5cc2be4779, which tries to reference a `text` attribute that does not exist in a string.

**Comment by SKaplanOfficial** [comment]
Ah, this is because I was testing support for using XAText objects there. I'll implement a fix with support for both XAText and str. In the meantime, you can create notes like this:
```python
PyXA.Application("Notes").new_note("PyXA Notes", PyXA.XAText("Example text of new note."))
```
