### ISSUE TITLE
ModuleNotFoundError: No module named 'PyXA.apps.Finder' - MacOS Application Issue

### ISSUE THREAD

**Issue by rathishkumar** [SKaplanOfficial/PyXA#14]
Hi @SKaplanOfficial 

Thanks for sharing this code.

I have been using the jxa script and running it from Python and it was working fine.

I have tested PyXA code and I found some issues/challenges. When executing directly from VS Code, it is working fine, But when I create a Mac App using Pyinstaller and executing throws an error. The same thing is happening with jxa script as well. I am new to MacOS development and don't have much idea about what is missing. 

Codesign:

```
dist/MyApp.app: valid on disk
dist/MyApp.app: satisfies its Designated Requirement
```
Error Message:

```
Traceback (most recent call last):
  File "myapp/app_observer.py", line 31, in get_window_title
  File "PyXA/XABase.py", line 1071, in __init__
  File "PyXA/XABase.py", line 1122, in __get_application
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyXA.apps.Chromium'

...

ModuleNotFoundError: No module named 'PyXA.apps.Console'

...

ModuleNotFoundError: No module named 'PyXA.apps.SystemEvents'
...

ModuleNotFoundError: No module named 'PyXA.apps.Finder'

```

I have used the below code to get front_window and storing the result in a log file.

```
import PyXA
import re

def get_window_title(active_app):
    app = PyXA.Application(active_app)
    window_title_str = str(app.front_window)

    # Use regular expression to extract the window title
    pattern = r">(.+?)>\s*$"
    match = re.search(pattern, window_title_str)
    window_title = match.group(1).strip()
    return window_title

```

As the code is working fine while running from vscode, I guess it is something to do with Mac OS permission. Please help.

**Comment by SKaplanOfficial** [comment]
Hi, that error is due to hidden imports, which you'll need to specify when running pyinstaller, e.g.:
```bash
pyinstaller test.py -F --hidden-import PyXA.apps.Finder --hidden-import PyXA.apps.SystemEvents
```
You'll need to specify each app the program will use, along with SystemEvents (since it's used to get process data). Once you include these, the app should run as expected.

This is a side-effect of dynamically loading app modules to improve overall performance.
