### ISSUE TITLE
install via conda: pyobjc & bs4 missing

### ISSUE THREAD

**Issue by jf---** [SKaplanOfficial/PyXA#2]
as it says on the tin; `pyobjc, bs4` seem
`pip install pyobjc` + `pip install bs4` fixed things.
Somewhat surprisingly, since by the looks of it, the `pyobjc` related deps are listed in `requirements.txt`, but `bs4` isn't

Super cool lib!

**Comment by SKaplanOfficial** [comment]
This should be all set in the latest version (0.0.8.3). Apparently, requirements.txt doesn't do anything when installing via pip the normal way. Now I know!
