### ISSUE TITLE
update pyobjc version

### ISSUE THREAD

**Issue by RhetTbull** [SKaplanOfficial/PyXA#3]
Is there a reason pyobjc is pinned to `8.5.1`?  The current version is `9.0.1` which adds support for `macOS 13` specific frameworks. I'm happy to test & submit a PR but wanted to first check to see if there's a reason for the specific version pin.

**Comment by SKaplanOfficial** [comment]
The 9.0 update changed some things and I haven't gotten the chance to test everything (partially because test coverage in general needs to improve). I should have more time in the coming week, though!
