### ISSUE TITLE
"Contributing Guidelines" link is broken in the README

### ISSUE THREAD

**Issue by RhetTbull** [SKaplanOfficial/PyXA#6]
Under the [contributing](https://github.com/SKaplanOfficial/PyXA#contributing) section of the README.md, the "Contributing Guidelines" link is broken and points to a 404: https://github.com/SKaplanOfficial/PyXA/blob/main/docs/about/contributing_guidelines.html

I'd submit a PR to fix it but not sure what the intended target is.

**Comment by SKaplanOfficial** [comment]
Thanks, just fixed this. Forgot to change it when I moved the guidelines to the standard markdown file a while back.
