### ISSUE TITLE
Unable to run tutorial - dependency issues & more

### ISSUE THREAD

**Issue by MizterB** [SKaplanOfficial/PyXA#7]
I am following the instructions at https://skaplanofficial.github.io/PyXA/tutorial/index.html in a fresh virtual environment.

When I get to the first run of `basics.py`, I get the error:
`ModuleNotFoundError: No module named 'macimg'`

If I `pip install macimg` and re-run `basics.py`, then I get:
`ModuleNotFoundError: No module named 'ApplicationServices'`

If I then `pip install pyobjc-framework-ApplicationServices` and re-run `basics.py`, I get:
`ModuleNotFoundError: No module named 'CoreText'`

If I then `pip install pyobjc-framework-CoreText` and re-run `basics.py`, it seems to satisfy the dependencies.  However, I then get a different error:
```
Traceback (most recent call last):
  File "/Users/me/temp/PyXA Examples/basics.py", line 3, in <module>
    print(PyXA.application("Safari").front_window.current_tab.url)
TypeError: 'NoneType' object is not callable
```

At this point, I don't know how to proceed - is this a code issue, or a documentation issue?  Any guidance is very much appreciated.

**Comment by SKaplanOfficial** [comment]
Hi @MizterB, thanks for reporting these issues! I will look into and resolve the dependency problems.

As for the error you're getting, this is a documentation issue which I've now resolved. Please try again with `application` capitalized, i.e.:
```
print(PyXA.Application("Safari").front_window.current_tab.url)
```
The lowercase form was removed in v0.2, and I thought I had updated all of the documentation accordingly. Please let me know if you encounter any further issues.

**Comment by MizterB** [comment]
Works perfectly now, I appreciate the quick response!  Very excited to start working with this...I was building my own tools for wrapping JXA in Python, and it wasn't very elegant.  What you've built here is far more comprehensive.  I look forward to using it.  Thank you for all your efforts!

**Comment by MizterB** [comment]
Leaving open if you want to track the dependency issues.

**Comment by edcnl** [comment]
Hello,
Followed the installation guide in a fresh virtual env, but after
```
python -m pip install mac-pyxa
```
I receive that
```
AttributeError: module 'PyXA' has no attribute 'Application'
```
